// Movesets for /pokemon attack, and the animation each move plays.

// Every move's animation: the effect it plays from hooks/effects/, and optionally a
// color, a power (1 or 2, for moves that share an effect at two sizes), and a line
// to print after "<Mon> used <Move>!"
export const MOVE_FX = {
  'Absorb': { effect: 'drain' },
  'Acid': { effect: 'acid' },
  'Acid Armor': { effect: 'acidarmor' },
  'Agility': { effect: 'agility' },
  'Amnesia': { effect: 'amnesia' },
  'Aurora Beam': { effect: 'aurorabeam' },
  'Barrage': { effect: 'eggbomb', power: 1 },
  'Barrier': { effect: 'barrier' },
  'Bind': { effect: 'wrap' },
  'Bite': { effect: 'bite' },
  'Blizzard': { effect: 'blizzard' },
  'Body Slam': { effect: 'bodyslam' },
  'Bone Club': { effect: 'boneclub' },
  'Bonemerang': { effect: 'bonemerang' },
  'Bubble': { effect: 'bubble' },
  'Bubble Beam': { effect: 'bubblebeam' },
  'Clamp': { effect: 'clamp' },
  'Comet Punch': { effect: 'cometpunch' },
  'Confuse Ray': { effect: 'confuseray' },
  'Confusion': { effect: 'confusion', color: 0xd88aff },
  'Crabhammer': { effect: 'crabhammer' },
  'Cut': { effect: 'cut' },
  'Defense Curl': { effect: 'defensecurl' },
  'Dig': { effect: 'dig' },
  'Double Kick': { effect: 'doublekick' },
  'Double Slap': { effect: 'doubleslap' },
  'Double Team': { effect: 'doubleteam' },
  'Dragon Rage': { effect: 'dragonrage' },
  'Dream Eater': { effect: 'dreameater' },
  'Drill Peck': { effect: 'drillpeck' },
  'Earthquake': { effect: 'earthquake' },
  'Egg Bomb': { effect: 'eggbomb', power: 2 },
  'Ember': { effect: 'ember' },
  'Explosion': { effect: 'explosion', power: 2 },
  'Fire Punch': { effect: 'firepunch' },
  'Fire Spin': { effect: 'firespin' },
  'Flamethrower': { effect: 'flamethrower' },
  'Fly': { effect: 'fly' },
  'Focus Energy': { effect: 'focusenergy' },
  'Fury Attack': { effect: 'furyattack' },
  'Fury Swipes': { effect: 'furyswipes' },
  'Growl': { effect: 'growl' },
  'Guillotine': { effect: 'guillotine' },
  'Gust': { effect: 'gust' },
  'Harden': { effect: 'harden' },
  'Headbutt': { effect: 'headbutt' },
  'Hi Jump Kick': { effect: 'hijumpkick' },
  'Horn Attack': { effect: 'hornattack' },
  'Horn Drill': { effect: 'horndrill' },
  'Hydro Pump': { effect: 'hydropump' },
  'Hyper Beam': { effect: 'hyperbeam' },
  'Hyper Fang': { effect: 'hyperfang' },
  'Hypnosis': { effect: 'hypnosis' },
  'Ice Beam': { effect: 'icebeam' },
  'Ice Punch': { effect: 'icepunch' },
  'Karate Chop': { effect: 'karatechop' },
  'Kinesis': { effect: 'kinesis' },
  'Leech Life': { effect: 'leechlife' },
  'Leech Seed': { effect: 'leechseed' },
  'Lick': { effect: 'lick' },
  'Light Screen': { effect: 'lightscreen' },
  'Lovely Kiss': { effect: 'lovelykiss' },
  'Low Kick': { effect: 'lowkick' },
  'Meditate': { effect: 'meditate' },
  'Mega Drain': { effect: 'drain', power: 2 },
  'Mega Kick': { effect: 'megakick' },
  'Mega Punch': { effect: 'megapunch' },
  'Minimize': { effect: 'minimize' },
  'Mist': { effect: 'mist' },
  'Night Shade': { effect: 'nightshade' },
  'Outrage': { effect: 'outrage' },
  'Pay Day': { effect: 'payday', text: 'Coins scattered everywhere!' },
  'Peck': { effect: 'peck' },
  'Petal Dance': { effect: 'petaldance' },
  'Pin Missile': { effect: 'pinmissile' },
  'Poison Gas': { effect: 'gas', color: 0x9a6ac8 },
  'Poison Powder': { effect: 'powder', color: 0xb45ad8 },
  'Poison Sting': { effect: 'poisonsting' },
  'Pound': { effect: 'pound' },
  'Psybeam': { effect: 'psybeam' },
  'Psychic': { effect: 'psychic' },
  'Quick Attack': { effect: 'quickattack' },
  'Rage': { effect: 'rage' },
  'Razor Leaf': { effect: 'razorleaf' },
  'Recover': { effect: 'recover' },
  'Reflect': { effect: 'reflect' },
  'Rest': { effect: 'rest', text: 'It started sleeping!' },
  'Roar': { effect: 'roar' },
  'Rock Slide': { effect: 'rockslide' },
  'Rock Throw': { effect: 'rockthrow' },
  'Sand Attack': { effect: 'sandattack' },
  'Scratch': { effect: 'scratch' },
  'Screech': { effect: 'screech' },
  'Seismic Toss': { effect: 'seismictoss' },
  'Self-Destruct': { effect: 'explosion', power: 1 },
  'Sing': { effect: 'sing' },
  'Skull Bash': { effect: 'skullbash' },
  'Sky Attack': { effect: 'skyattack' },
  'Slam': { effect: 'slam' },
  'Slash': { effect: 'slash' },
  'Sleep Powder': { effect: 'powder', color: 0x8fd0ff },
  'Sludge': { effect: 'sludge', color: 0x9a5ac8 },
  'Smog': { effect: 'gas', color: 0x8a7a6a },
  'Smokescreen': { effect: 'gas', color: 0x55555f, power: 2 },
  'Soft-Boiled': { effect: 'softboiled' },
  'Solar Beam': { effect: 'solarbeam' },
  'Spike Cannon': { effect: 'spikecannon' },
  'Splash': { effect: 'splash', text: 'But nothing happened!' },
  'Spore': { effect: 'powder', color: 0xd8b46a },
  'Stomp': { effect: 'stomp' },
  'String Shot': { effect: 'stringshot' },
  'Stun Spore': { effect: 'powder', color: 0xf2d22e },
  'Submission': { effect: 'submission' },
  'Supersonic': { effect: 'supersonic' },
  'Surf': { effect: 'surf' },
  'Swift': { effect: 'swift' },
  'Tackle': { effect: 'tackle' },
  'Take Down': { effect: 'takedown' },
  'Teleport': { effect: 'teleport' },
  'Thrash': { effect: 'thrash' },
  'Thunder': { effect: 'thunder' },
  'Thunder Punch': { effect: 'thunderpunch' },
  'Thunder Shock': { effect: 'thundershock' },
  'Thunder Wave': { effect: 'thunderwave' },
  'Thunderbolt': { effect: 'thunderbolt' },
  'Transform': { effect: 'transform' },
  'Tri Attack': { effect: 'triattack' },
  'Twineedle': { effect: 'twineedle' },
  'Vice Grip': { effect: 'vicegrip' },
  'Vine Whip': { effect: 'vinewhip' },
  'Water Gun': { effect: 'watergun' },
  'Waterfall': { effect: 'waterfall' },
  'Wing Attack': { effect: 'wingattack' },
  'Withdraw': { effect: 'withdraw' },
  'Wrap': { effect: 'wrap' },
}

// Each mon's moveset: move names, or { name, ...options } for options only that mon
// uses: from: 'top' for the moves the Bulbasaur line sends out of its bulb,
// from: 'body' for the smog Koffing and Weezing pour from their whole body, and
// mouth: for how far down the sprite a move leaves the mouth, when 0.35 misses it
export const MOVES = {
  abra: ['Teleport', 'Confusion'],
  aerodactyl: ['Wing Attack', 'Bite', 'Hyper Beam', 'Supersonic'],
  alakazam: ['Psychic', 'Kinesis', 'Recover', 'Reflect'],
  arbok: ['Wrap', 'Poison Sting', 'Bite', 'Acid'],
  arcanine: ['Flamethrower', 'Take Down', 'Bite', 'Agility'],
  articuno: ['Ice Beam', 'Blizzard', 'Agility', 'Mist'],
  beedrill: ['Twineedle', 'Fury Attack', 'Agility'],
  bellsprout: ['Vine Whip', 'Sleep Powder', 'Acid'],
  blastoise: ['Hydro Pump', 'Bite', 'Withdraw', 'Skull Bash'],
  bulbasaur: [{ name: 'Vine Whip', from: 'top' }, 'Razor Leaf', 'Leech Seed', { name: 'Sleep Powder', from: 'top' }],
  butterfree: ['Confusion', 'Sleep Powder', 'Stun Spore', 'Gust'],
  caterpie: ['String Shot', 'Tackle'],
  chansey: ['Soft-Boiled', 'Sing', 'Double Slap', 'Minimize'],
  charizard: ['Flamethrower', 'Slash', 'Wing Attack', 'Seismic Toss'],
  charmander: ['Ember', 'Scratch', 'Growl', 'Smokescreen'],
  charmeleon: ['Flamethrower', 'Slash', 'Rage', 'Smokescreen'],
  clefable: ['Sing', 'Double Slap', 'Minimize'],
  clefairy: ['Sing', 'Pound', 'Minimize'],
  cloyster: ['Clamp', 'Spike Cannon', 'Aurora Beam', 'Withdraw'],
  cubone: ['Bone Club', 'Headbutt', 'Growl'],
  dewgong: ['Aurora Beam', 'Headbutt', 'Rest'],
  diglett: ['Dig', 'Scratch', 'Earthquake', 'Sand Attack'],
  ditto: ['Transform'],
  dodrio: ['Drill Peck', 'Tri Attack', 'Agility'],
  doduo: ['Peck', 'Agility', 'Growl'],
  dragonair: ['Dragon Rage', 'Wrap', 'Thunder Wave', 'Agility'],
  dragonite: ['Hyper Beam', 'Outrage', 'Wing Attack', 'Thunder Punch'],
  dratini: ['Wrap', 'Thunder Wave', 'Dragon Rage'],
  drowzee: ['Hypnosis', 'Confusion', 'Dream Eater', 'Headbutt'],
  dugtrio: ['Dig', 'Slash', 'Earthquake', 'Sand Attack'],
  eevee: ['Quick Attack', 'Sand Attack', 'Bite', 'Growl'],
  ekans: ['Wrap', 'Poison Sting', 'Bite'],
  electabuzz: ['Thunder Punch', 'Thunderbolt', 'Light Screen', 'Quick Attack'],
  electrode: ['Explosion', 'Screech', 'Swift', 'Thunder Shock'],
  exeggcute: ['Hypnosis', 'Leech Seed', 'Barrage'],
  exeggutor: ['Solar Beam', 'Stomp', 'Hypnosis', 'Egg Bomb'],
  farfetchd: ['Cut', 'Fury Attack', 'Agility'],
  fearow: ['Drill Peck', 'Agility', 'Fly'],
  flareon: ['Flamethrower', 'Quick Attack', 'Bite', 'Smog'],
  gastly: [{ name: 'Lick', mouth: 0.65 }, 'Night Shade', 'Hypnosis', 'Confuse Ray'],
  gengar: ['Night Shade', 'Hypnosis', { name: 'Lick', mouth: 0.55 }, 'Dream Eater'],
  geodude: ['Rock Throw', 'Tackle', 'Defense Curl', 'Self-Destruct'],
  gloom: ['Absorb', 'Poison Powder', 'Acid', 'Petal Dance'],
  golbat: ['Leech Life', 'Wing Attack', 'Supersonic', 'Bite'],
  goldeen: ['Horn Attack', 'Supersonic', 'Waterfall'],
  golduck: ['Confusion', 'Hydro Pump', 'Fury Swipes', 'Amnesia'],
  golem: ['Rock Slide', 'Earthquake', 'Explosion', 'Defense Curl'],
  graveler: ['Rock Throw', 'Earthquake', 'Self-Destruct', 'Defense Curl'],
  grimer: ['Pound', 'Poison Gas', 'Sludge', 'Minimize'],
  growlithe: ['Ember', 'Bite', 'Roar', 'Take Down'],
  gyarados: ['Hyper Beam', 'Dragon Rage', 'Hydro Pump', 'Bite'],
  haunter: [{ name: 'Lick', mouth: 0.45 }, 'Night Shade', 'Hypnosis', 'Confuse Ray'],
  hitmonchan: ['Fire Punch', 'Ice Punch', 'Thunder Punch', 'Agility'],
  hitmonlee: ['Hi Jump Kick', 'Mega Kick', 'Meditate'],
  horsea: ['Bubble', 'Smokescreen', 'Water Gun'],
  hypno: ['Hypnosis', 'Psychic', 'Dream Eater', 'Headbutt'],
  ivysaur: ['Razor Leaf', { name: 'Vine Whip', from: 'top' }, { name: 'Poison Powder', from: 'top' }, 'Leech Seed'],
  jigglypuff: ['Sing', 'Pound', 'Rest', 'Defense Curl'],
  jolteon: ['Thunderbolt', 'Pin Missile', 'Quick Attack', 'Agility'],
  jynx: ['Lovely Kiss', 'Ice Punch', 'Blizzard', 'Psychic'],
  kabuto: ['Scratch', 'Harden', 'Absorb'],
  kabutops: ['Slash', 'Hydro Pump', 'Absorb', 'Harden'],
  kadabra: ['Teleport', 'Kinesis', 'Psybeam', 'Recover'],
  kakuna: ['Harden'],
  kangaskhan: ['Comet Punch', 'Rage', 'Bite', 'Earthquake'],
  kingler: ['Crabhammer', 'Guillotine', 'Bubble', 'Stomp'],
  koffing: ['Tackle', { name: 'Smog', from: 'body' }, 'Sludge', 'Self-Destruct'],
  krabby: ['Bubble', 'Vice Grip', 'Harden', 'Crabhammer'],
  lapras: ['Surf', 'Ice Beam', 'Sing', 'Body Slam'],
  lickitung: [{ name: 'Lick', mouth: 0.45 }, 'Wrap', 'Stomp', 'Supersonic'],
  machamp: ['Karate Chop', 'Seismic Toss', 'Submission', 'Earthquake'],
  machoke: ['Karate Chop', 'Seismic Toss', 'Focus Energy'],
  machop: ['Karate Chop', 'Low Kick', 'Seismic Toss'],
  magikarp: ['Splash', 'Tackle'],
  magmar: ['Fire Punch', 'Flamethrower', 'Smog', 'Confuse Ray'],
  magnemite: ['Thunder Shock', 'Supersonic', 'Swift'],
  magneton: ['Thunderbolt', 'Supersonic', 'Swift'],
  mankey: ['Karate Chop', 'Low Kick', 'Thrash', 'Screech'],
  marowak: ['Bonemerang', 'Bone Club', 'Thrash'],
  meowth: ['Pay Day', 'Fury Swipes', 'Bite', 'Screech'],
  metapod: ['Harden'],
  mew: ['Psychic', 'Transform', 'Mega Punch'],
  mewtwo: ['Psychic', 'Barrier', 'Recover', 'Swift'],
  moltres: ['Fire Spin', 'Sky Attack', 'Agility', 'Peck'],
  mrmime: ['Barrier', 'Confusion', 'Double Slap'],
  muk: ['Sludge', 'Poison Gas', 'Body Slam', 'Acid Armor'],
  nidoking: ['Horn Attack', 'Poison Sting', 'Earthquake', 'Double Kick'],
  nidoqueen: ['Body Slam', 'Poison Sting', 'Scratch', 'Earthquake'],
  nidoran_female: ['Scratch', 'Poison Sting', 'Growl'],
  nidoran_male: ['Horn Attack', 'Poison Sting', 'Double Kick'],
  nidorina: ['Scratch', 'Bite', 'Poison Sting'],
  nidorino: ['Horn Attack', 'Poison Sting', 'Double Kick'],
  ninetales: ['Flamethrower', 'Confuse Ray', 'Quick Attack'],
  oddish: ['Absorb', 'Sleep Powder', 'Acid'],
  omanyte: ['Water Gun', 'Withdraw', 'Horn Attack'],
  omastar: ['Hydro Pump', 'Spike Cannon', 'Withdraw', 'Horn Attack'],
  onix: ['Rock Throw', 'Bind', 'Slam', 'Harden'],
  paras: ['Scratch', 'Stun Spore', 'Leech Life'],
  parasect: ['Spore', 'Slash', 'Leech Life'],
  persian: ['Slash', 'Pay Day', 'Bite', 'Screech'],
  pidgeot: ['Wing Attack', 'Quick Attack', 'Agility', 'Sand Attack'],
  pidgeotto: ['Gust', 'Quick Attack', 'Sand Attack'],
  pidgey: ['Gust', 'Sand Attack', 'Quick Attack'],
  pikachu: ['Thunderbolt', 'Quick Attack', 'Thunder', 'Agility'],
  pikachu_female: ['Thunderbolt', 'Quick Attack', 'Thunder', 'Agility'],
  pinsir: ['Vice Grip', 'Seismic Toss', 'Guillotine', 'Harden'],
  poliwag: ['Bubble', 'Hypnosis', 'Water Gun'],
  poliwhirl: ['Water Gun', 'Hypnosis', 'Double Slap', 'Body Slam'],
  poliwrath: ['Submission', 'Hydro Pump', 'Hypnosis', 'Body Slam'],
  ponyta: ['Ember', 'Stomp', 'Agility'],
  porygon: ['Psybeam', 'Tri Attack', 'Agility', 'Recover'],
  primeape: ['Fury Swipes', 'Seismic Toss', 'Thrash', 'Screech'],
  psyduck: ['Confusion', 'Scratch', 'Water Gun'],
  raichu: ['Thunderbolt', 'Thunder Wave', 'Quick Attack', 'Swift'],
  rapidash: ['Fire Spin', 'Stomp', 'Agility'],
  raticate: ['Hyper Fang', 'Quick Attack', 'Focus Energy'],
  rattata: ['Quick Attack', 'Hyper Fang'],
  rhydon: ['Horn Drill', 'Earthquake', 'Rock Slide'],
  rhyhorn: ['Horn Attack', 'Fury Attack', 'Rock Slide'],
  sandshrew: ['Scratch', 'Sand Attack', 'Defense Curl'],
  sandslash: ['Slash', 'Sand Attack', 'Poison Sting', 'Swift'],
  scyther: ['Slash', 'Quick Attack', 'Double Team', 'Wing Attack'],
  seadra: ['Hydro Pump', 'Smokescreen', 'Agility', 'Bubble Beam'],
  seaking: ['Horn Drill', 'Waterfall', 'Supersonic', 'Agility'],
  seel: ['Headbutt', 'Aurora Beam', 'Rest', 'Growl'],
  shellder: ['Withdraw', 'Supersonic', 'Clamp', 'Aurora Beam'],
  slowbro: ['Psychic', 'Withdraw', 'Water Gun', 'Headbutt'],
  slowpoke: ['Confusion', 'Water Gun', 'Headbutt', 'Amnesia'],
  snorlax: ['Rest', 'Body Slam', 'Amnesia', 'Hyper Beam'],
  spearow: ['Peck', 'Growl', 'Agility'],
  squirtle: ['Tackle', 'Bubble', 'Water Gun', 'Withdraw'],
  starmie: ['Swift', 'Hydro Pump', 'Recover', 'Psychic'],
  staryu: ['Water Gun', 'Swift', 'Recover', 'Harden'],
  tangela: ['Vine Whip', 'Absorb', 'Stun Spore', 'Slam'],
  tauros: ['Take Down', 'Earthquake', 'Hyper Beam'],
  tentacool: ['Acid', 'Wrap', 'Supersonic'],
  tentacruel: ['Hydro Pump', 'Wrap', 'Acid', 'Barrier'],
  vaporeon: ['Hydro Pump', 'Aurora Beam', 'Quick Attack', 'Acid Armor'],
  venomoth: ['Psybeam', 'Poison Powder', 'Leech Life', 'Supersonic'],
  venonat: ['Tackle', 'Poison Powder', 'Leech Life', 'Confusion'],
  venusaur: ['Solar Beam', 'Razor Leaf', { name: 'Vine Whip', from: 'top' }, { name: 'Sleep Powder', from: 'top' }],
  venusaur_female: [
    'Solar Beam', 'Razor Leaf', { name: 'Vine Whip', from: 'top' }, { name: 'Sleep Powder', from: 'top' }
  ],
  victreebel: ['Razor Leaf', 'Vine Whip', 'Acid', 'Stun Spore'],
  vileplume: ['Petal Dance', 'Stun Spore', 'Acid', 'Mega Drain'],
  voltorb: ['Tackle', 'Screech', 'Self-Destruct', 'Thunder Wave'],
  vulpix: ['Ember', 'Quick Attack', 'Confuse Ray'],
  wartortle: ['Water Gun', 'Bite', 'Withdraw', 'Skull Bash'],
  weedle: ['Poison Sting', 'String Shot'],
  weepinbell: ['Razor Leaf', 'Wrap', 'Acid', 'Sleep Powder'],
  weezing: [{ name: 'Smog', from: 'body' }, 'Sludge', 'Explosion', 'Tackle'],
  wigglytuff: ['Sing', 'Double Slap', 'Body Slam', 'Rest'],
  zapdos: ['Thunder', 'Drill Peck', 'Agility', 'Light Screen'],
  zubat: ['Leech Life', 'Supersonic', 'Wing Attack'],
}

// A mon's moves, each with its effect and options filled in
export function movesOf(mon) {
  return (MOVES[mon] ?? []).map((entry) => {
    const own = typeof entry === 'string' ? { name: entry } : entry
    return { ...MOVE_FX[own.name], ...own }
  })
}
